# Base ONNX cache variables shared across all platforms.

set(CMAKE_BUILD_TYPE Release CACHE STRING "")
set(ONNX_USE_LITE_PROTO ON CACHE BOOL "")
set(ONNX_USE_PROTOBUF_SHARED_LIBS OFF CACHE BOOL "")
set(ONNX_GEN_PB_TYPE_STUBS OFF CACHE BOOL "")
set(ONNX_ML 0 CACHE STRING "")
set(ONNX_BUILD_CUSTOM_PROTOBUF ON CACHE BOOL "")

# set(CMAKE_CXX_FLAGS "/include cstdint" CACHE STRING "")
