# x86-64-specific OpenVINO cache variables.

set(ENABLE_INTEL_CPU ON CACHE BOOL "")
set(ENABLE_INTEL_GPU ON CACHE BOOL "")
set(ENABLE_ONEDNN_FOR_GPU ON CACHE BOOL "")
set(ENABLE_INTEL_NPU ON CACHE BOOL "")
