name: Setup ONNX (Windows)
description: Compiles ONNX from source on Windows
inputs:
  onnx-tag:
    description: The Git tag or commit hash of ONNX to build
    required: true

runs:
  using: composite
  steps:
    - name: Define cache key
      id: cache-key
      shell: pwsh
      run: |
        "key=${{ format(
          'setup-onnx-{0}-{1}-{2}',
          runner.os,
          inputs.onnx-tag,
          hashFiles('.github/cmake-cache/onnx-base.cmake', '.github/cmake-cache/onnx-windows.cmake')
        ) }}" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

    - name: Restore ONNX
      id: cache-onnx
      uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
      with:
        path: onnx-dist
        key: ${{ steps.cache-key.outputs.key }}

    - name: Checkout onnx
      if: steps.cache-onnx.outputs.cache-hit != 'true'
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      with:
        repository: onnx/onnx
        ref: ${{ inputs.onnx-tag }}
        path: onnx
        submodules: recursive

    - name: Configure ONNX
      shell: pwsh
      if: steps.cache-onnx.outputs.cache-hit != 'true'
      run: cmake -S onnx -B build_onnx -G Ninja -LA
        -C "$env:GITHUB_WORKSPACE\.github\cmake-cache\onnx-base.cmake"
        -C "$env:GITHUB_WORKSPACE\.github\cmake-cache\onnx-windows.cmake"

    - name: Build onnx
      shell: pwsh
      if: steps.cache-onnx.outputs.cache-hit != 'true'
      run: cmake --build build_onnx

    - name: Install ONNX
      shell: pwsh
      if: steps.cache-onnx.outputs.cache-hit != 'true'
      run: cmake --install build_onnx --prefix onnx-dist

    - name: Save ONNX
      if: steps.cache-onnx.outputs.cache-hit != 'true'
      uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
      with:
        path: onnx-dist
        key: ${{ steps.cache-key.outputs.key }}

    - name: Configure ONNX Path
      shell: pwsh
      run: |
        $onnxRoot = (Resolve-Path "onnx-dist").Path
        "CMAKE_PREFIX_PATH=$onnxRoot;$env:CMAKE_PREFIX_PATH".TrimEnd(';') | Out-File -FilePath $env:GITHUB_ENV -Append
